version : "3"
services :
  redis:
    image: redis:latest
    container_name: redis
    hostname: test
    ports:
      - "6379:6379"
  mysql:
    image: mysql:8.0
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    container_name: my-mysql